Update run-dbt-prod.yml

diff --git a/.github/workflows/run-dbt-prod.yml b/.github/workflows/run-dbt-prod.yml
--- a/.github/workflows/run-dbt-prod.yml
+++ b/.github/workflows/run-dbt-prod.yml
@@ -5,8 +5,6 @@ on:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-  # schedule:
-  #   - cron: '0 8 * * *'
 
 env:
   DBT_PROFILES_DIR: ./nyc_parking_violations
@@ -14,24 +12,32 @@ env:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v3
+
     - name: Set up Python 3.12
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v4
       with:
         python-version: "3.12"
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        pip install dbt-duckdb  # Explicitly install the dbt-duckdb adapter
+
+    - name: Clear dbt Cache
+      run: rm -rf ~/.dbt
+
+    - name: Check Database File
+      run: ls -lh ./Data/ || echo "Database directory missing"
+
     - name: Run dbt Prod
       run: |
         dbt debug
         dbt compile --target prod
         dbt run --target prod
+
     - name: Test dbt Prod
-      run: |
-        dbt test --target prod
+      run: dbt test --target prod
